#urls.py - URL patterns for Guestbook App
from django.conf.urls.defaults import *

urlpatterns = patterns('appcode.views',
                       url(r'^$', 'home', name='apphome'),
                       url(r'^login$', 'login', name='login'),
                       url(r'^logout$','logout', name='logout'),
                       url(r'^load_account$','load_account', name='load_account'),
                       url(r'^destroy$','destroy', name='destroy'),
                       url(r'^share_login$','share_login', name='share_login'),
                       url(r'^track_share$','track_share', name='track_share'),
                       url(r'^create_island$','create_island', name='create_island'),
                       url(r'^join_island$','join_island', name='join_island'),
                       url(r'^subscribe_login$','subscribe_login', name='subscribe_login'),
                       url(r'^get_all_island$','get_all_island', name='get_all_island'),
                       url(r'^get_account_players$','get_account_players', name='get_account_players'),
                       url(r'^buy_plant$','buy_plant', name='by_plant'),
                       url(r'^load_player$','load_player', name='load_player'),
                       url(r'^play$','play', name='play'),
                       url(r'^hire_worker$','hire_worker', name='hire'),
                       url(r'^manufacture_shoe$','manufacture_shoe', name='manufacture_shoe'),
                       url(r'^retrieve_player_plants$','retrieve_player_plants', name='retrieve_player_plants'),
                       url(r'^system_buy_shoes$','system_buy_shoes', name='system_buy_shoes'),
                       url(r'^island_ranking$','island_ranking', name='island_ranking'),
                       url(r'^retrieve_past_production$','retrieve_past_production', name='past_production'),
                       url(r'^buy_credits_fail$','buy_credits_fail', name='buy_credits_fail'),
                       url(r'^buy_credits$','buy_credits', name='buy_credits'),
                       url(r'^demand_supply','demand_supply', name='demand_supply'),
)